#include "ability.h"
#include "eventHandlers.h"
//stub function, autogenerated
void FlashAbilityColor() {
 
}

//stub function, autogenerated
voidSavePause() {
 
}

//stub function, autogenerated
voidSaveAbility() {
 
}

//stub function, autogenerated
voidFlashWrong() {
 
}

//stub function, autogenerated
voidStartAbility() {
 
}